# Generated by Django 2.2.1 on 2019-06-17 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20190617_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='vote',
        ),
    ]
