# Generated by Django 2.2.1 on 2019-06-19 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20190617_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name': 'comment'},
        ),
    ]
